[package]
name = "ez-tftpd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
async-tftp = "0.3.6"
fern = "0.6.1"
futures-lite = "1.12.0"
log = "0.4.17"
smol = "1.3.0"
